version: "3.9"
services:
  tucomanda:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=deusigs
      - MONGO_INITDB_ROOT_PASSWORD=plokio
    volumes:
      - mongo-data:/data/db
      #mysql -> /var/lib/mysql
      #postgres -> /var/lib/postgresql/data
volumes:
  mongo-data: